2021-03-21 20:53:22,399 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 20:53:37,234 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:00:37,350 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:00:39,456 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:01:47,441 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:02:02,674 -- [test_register.py-->line:49] - ERROR: 用例--注册成功-不带注册名--执行未通过
2021-03-21 21:02:02,674 -- [test_register.py-->line:50] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:02:02,674 -- [test_register.py-->line:51] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:02:02,674 -- [test_register.py-->line:52] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 42, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:02:05,763 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:08:32,842 -- [test_register.py-->line:49] - ERROR: 用例--注册成功-带注册名--执行未通过
2021-03-21 21:08:32,842 -- [test_register.py-->line:50] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:08:32,842 -- [test_register.py-->line:51] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:08:32,842 -- [test_register.py-->line:52] - ERROR:  :: 2 != 0
Traceback (most recent call last):
  File "E:\pycharm\PyCharm 2018.1.2\helpers\pycharm\teamcity\diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 42, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\pycharm\PyCharm 2018.1.2\helpers\pycharm\teamcity\diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: 2 != 0
2021-03-21 21:08:33,185 -- [test_register.py-->line:49] - ERROR: 用例--注册成功-不带注册名--执行未通过
2021-03-21 21:08:33,185 -- [test_register.py-->line:50] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:08:33,185 -- [test_register.py-->line:51] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:08:33,185 -- [test_register.py-->line:52] - ERROR:  :: 2 != 0
Traceback (most recent call last):
  File "E:\pycharm\PyCharm 2018.1.2\helpers\pycharm\teamcity\diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 42, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\pycharm\PyCharm 2018.1.2\helpers\pycharm\teamcity\diff_tools.py", line 38, in _patched_equals
    raise error
teamcity.diff_tools.EqualsAssertionError:  :: 2 != 0
2021-03-21 21:11:51,541 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:11:53,507 -- [test_register.py-->line:50] - ERROR: 用例--注册成功-带注册名--执行未通过
2021-03-21 21:11:53,507 -- [test_register.py-->line:51] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:11:53,507 -- [test_register.py-->line:52] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:11:53,507 -- [test_register.py-->line:53] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 43, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:11:53,803 -- [test_register.py-->line:50] - ERROR: 用例--注册成功-不带注册名--执行未通过
2021-03-21 21:11:53,803 -- [test_register.py-->line:51] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:11:53,803 -- [test_register.py-->line:52] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:11:53,803 -- [test_register.py-->line:53] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 43, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:11:54,583 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:18:14,385 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:18:19,283 -- [test_register.py-->line:50] - ERROR: 用例--注册成功-不带注册名--执行未通过
2021-03-21 21:18:19,283 -- [test_register.py-->line:51] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:18:19,283 -- [test_register.py-->line:52] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:18:19,283 -- [test_register.py-->line:53] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 43, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:18:19,595 -- [test_register.py-->line:57] - INFO: 用例--不输入手机号--执行通过
2021-03-21 21:18:19,907 -- [test_register.py-->line:57] - INFO: 用例--手机号长度10位--执行通过
2021-03-21 21:18:20,235 -- [test_register.py-->line:57] - INFO: 用例--手机号长度12位--执行通过
2021-03-21 21:18:20,516 -- [test_register.py-->line:57] - INFO: 用例--手机号含有非法字符--执行通过
2021-03-21 21:18:20,937 -- [test_register.py-->line:57] - INFO: 用例--已注册过的手机号--执行通过
2021-03-21 21:18:21,233 -- [test_register.py-->line:57] - INFO: 用例--密码7位--执行通过
2021-03-21 21:18:21,499 -- [test_register.py-->line:57] - INFO: 用例--密码17位--执行通过
2021-03-21 21:18:21,748 -- [test_register.py-->line:57] - INFO: 用例--不输入密码--执行通过
2021-03-21 21:18:22,029 -- [test_register.py-->line:57] - INFO: 用例--注册名11位--执行通过
2021-03-21 21:18:22,294 -- [test_register.py-->line:57] - INFO: 用例--类型输入非0，1内容--执行通过
2021-03-21 21:18:22,528 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:30:51,964 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:30:54,133 -- [test_register.py-->line:50] - ERROR: 用例--注册成功-带注册名--执行未通过
2021-03-21 21:30:54,133 -- [test_register.py-->line:51] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:30:54,133 -- [test_register.py-->line:52] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:30:54,133 -- [test_register.py-->line:53] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 43, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:30:54,552 -- [test_register.py-->line:50] - ERROR: 用例--注册成功-不带注册名--执行未通过
2021-03-21 21:30:54,552 -- [test_register.py-->line:51] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:30:54,552 -- [test_register.py-->line:52] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:30:54,552 -- [test_register.py-->line:53] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 43, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:30:54,892 -- [test_register.py-->line:57] - INFO: 用例--不输入手机号--执行通过
2021-03-21 21:30:55,195 -- [test_register.py-->line:57] - INFO: 用例--手机号长度10位--执行通过
2021-03-21 21:30:55,495 -- [test_register.py-->line:57] - INFO: 用例--手机号长度12位--执行通过
2021-03-21 21:30:55,775 -- [test_register.py-->line:57] - INFO: 用例--手机号含有非法字符--执行通过
2021-03-21 21:30:59,146 -- [test_register.py-->line:57] - INFO: 用例--已注册过的手机号--执行通过
2021-03-21 21:31:02,468 -- [test_register.py-->line:57] - INFO: 用例--密码7位--执行通过
2021-03-21 21:31:02,769 -- [test_register.py-->line:57] - INFO: 用例--密码17位--执行通过
2021-03-21 21:31:06,076 -- [test_register.py-->line:57] - INFO: 用例--不输入密码--执行通过
2021-03-21 21:31:06,375 -- [test_register.py-->line:57] - INFO: 用例--注册名11位--执行通过
2021-03-21 21:31:06,705 -- [test_register.py-->line:57] - INFO: 用例--类型输入非0，1内容--执行通过
2021-03-21 21:31:06,962 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:31:06,962 -- [run.py-->line:15] - INFO: 
2021-03-21 21:31:06,962 -- [run.py-->line:16] - INFO: 
2021-03-21 21:31:52,146 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:31:54,045 -- [test_register.py-->line:51] - ERROR: 用例--注册成功-带注册名--执行未通过
2021-03-21 21:31:54,045 -- [test_register.py-->line:52] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:31:54,045 -- [test_register.py-->line:53] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:31:54,055 -- [test_register.py-->line:54] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 44, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:31:54,527 -- [test_register.py-->line:51] - ERROR: 用例--注册成功-不带注册名--执行未通过
2021-03-21 21:31:54,527 -- [test_register.py-->line:52] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-21 21:31:54,527 -- [test_register.py-->line:53] - DEBUG: 实际结果：{'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-21 21:31:54,527 -- [test_register.py-->line:54] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_register.py", line 44, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-21 21:31:54,879 -- [test_register.py-->line:58] - INFO: 用例--不输入手机号--执行通过
2021-03-21 21:31:55,205 -- [test_register.py-->line:58] - INFO: 用例--手机号长度10位--执行通过
2021-03-21 21:31:55,505 -- [test_register.py-->line:58] - INFO: 用例--手机号长度12位--执行通过
2021-03-21 21:31:55,825 -- [test_register.py-->line:58] - INFO: 用例--手机号含有非法字符--执行通过
2021-03-21 21:31:56,116 -- [test_register.py-->line:58] - INFO: 用例--已注册过的手机号--执行通过
2021-03-21 21:31:56,406 -- [test_register.py-->line:58] - INFO: 用例--密码7位--执行通过
2021-03-21 21:31:56,707 -- [test_register.py-->line:58] - INFO: 用例--密码17位--执行通过
2021-03-21 21:31:57,001 -- [test_register.py-->line:58] - INFO: 用例--不输入密码--执行通过
2021-03-21 21:31:57,291 -- [test_register.py-->line:58] - INFO: 用例--注册名11位--执行通过
2021-03-21 21:31:57,591 -- [test_register.py-->line:58] - INFO: 用例--类型输入非0，1内容--执行通过
2021-03-21 21:31:57,841 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------
2021-03-21 21:31:57,841 -- [run.py-->line:15] - INFO: 
2021-03-21 21:31:57,841 -- [run.py-->line:16] - INFO: 
2021-03-21 21:35:32,136 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-21 21:35:34,397 -- [test_register.py-->line:58] - INFO: 用例--注册成功-带注册名--执行通过
2021-03-21 21:35:35,074 -- [test_register.py-->line:58] - INFO: 用例--注册成功-不带注册名--执行通过
2021-03-21 21:35:35,390 -- [test_register.py-->line:58] - INFO: 用例--不输入手机号--执行通过
2021-03-21 21:35:35,685 -- [test_register.py-->line:58] - INFO: 用例--手机号长度10位--执行通过
2021-03-21 21:35:35,963 -- [test_register.py-->line:58] - INFO: 用例--手机号长度12位--执行通过
2021-03-21 21:35:36,284 -- [test_register.py-->line:58] - INFO: 用例--手机号含有非法字符--执行通过
2021-03-21 21:35:36,645 -- [test_register.py-->line:58] - INFO: 用例--已注册过的手机号--执行通过
2021-03-21 21:35:36,943 -- [test_register.py-->line:58] - INFO: 用例--密码7位--执行通过
2021-03-21 21:35:37,223 -- [test_register.py-->line:58] - INFO: 用例--密码17位--执行通过
2021-03-21 21:35:40,498 -- [test_register.py-->line:58] - INFO: 用例--不输入密码--执行通过
2021-03-21 21:35:40,789 -- [test_register.py-->line:58] - INFO: 用例--注册名11位--执行通过
2021-03-21 21:35:44,078 -- [test_register.py-->line:58] - INFO: 用例--类型输入非0，1内容--执行通过
2021-03-21 21:35:44,405 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-24 22:03:10,076 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-24 22:03:32,829 -- [test_login.py-->line:44] - ERROR: 用例--登录成功--执行未通过
2021-03-24 22:03:32,829 -- [test_login.py-->line:45] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-24 22:03:32,829 -- [test_login.py-->line:46] - DEBUG: 实际结果：{'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-24 22:03:32,829 -- [test_login.py-->line:47] - ERROR: 1001 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_login.py", line 41, in test_register
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1001 != 0
2021-03-24 22:03:33,344 -- [test_login.py-->line:51] - INFO: 用例--手机号为空--执行通过
2021-03-24 22:03:36,698 -- [test_login.py-->line:51] - INFO: 用例--密码为空--执行通过
2021-03-24 22:03:37,072 -- [test_login.py-->line:51] - INFO: 用例--手机号未注册--执行通过
2021-03-24 22:03:37,587 -- [test_login.py-->line:51] - INFO: 用例--密码错误--执行通过
2021-03-24 22:03:37,868 -- [test_login.py-->line:51] - INFO: 用例--手机号格式错误--执行通过
2021-03-24 22:03:38,164 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:04:21,287 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:04:38,323 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:05:30,801 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:05:32,673 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:09:07,252 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:09:08,936 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:10:10,759 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:10:12,553 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:16:19,872 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:16:21,572 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:17:39,978 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:17:41,897 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:17:41,959 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:17:42,006 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:17:42,037 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:22:32,305 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:22:34,333 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:22:34,396 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:22:34,474 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:22:34,521 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:24:39,621 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:24:41,478 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:24:41,961 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:24:42,289 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:24:42,554 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:27:27,867 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:27:29,693 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:27:29,958 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:27:30,239 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:27:30,488 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:41:10,045 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:41:16,098 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:41:25,052 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:41:26,035 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:41:26,799 -- [test_recharge.py-->line:62] - ERROR: 用例--会员id为字符串--执行未通过
2021-03-27 12:41:26,799 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '数字格式化异常'}
2021-03-27 12:41:26,799 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 502400.32, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:41:26,799 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:41:27,735 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为小数--执行通过
2021-03-27 12:41:29,405 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额为0--执行未通过
2021-03-27 12:41:29,405 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 12:41:29,405 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 502400.32, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:41:29,405 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:41:29,857 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额为负数--执行通过
2021-03-27 12:41:30,465 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额为空--执行未通过
2021-03-27 12:41:30,465 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 1, 'msg': '充值金额为空'}
2021-03-27 12:41:30,465 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 2, 'msg': '余额必须为数值型', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:41:30,465 -- [test_recharge.py-->line:65] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-03-27 12:41:31,011 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额-3位小数--执行未通过
2021-03-27 12:41:31,011 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额小数超过两位'}
2021-03-27 12:41:31,011 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 2, 'msg': '余额小数超过两位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:41:31,011 -- [test_recharge.py-->line:65] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 53, in test_recharge
    self.assertEqual(res["msg"], expected["msg"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 1202, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "E:\python\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-03-27 12:41:31,557 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额-大于50万--执行未通过
2021-03-27 12:41:31,557 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 12:41:31,557 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:41:31,557 -- [test_recharge.py-->line:65] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 53, in test_recharge
    self.assertEqual(res["msg"], expected["msg"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 1202, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "E:\python\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-03-27 12:41:32,353 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-非数字--执行通过
2021-03-27 12:41:32,618 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:44:11,461 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:44:13,426 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:44:13,769 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-整数--执行通过
2021-03-27 12:44:14,159 -- [test_recharge.py-->line:62] - ERROR: 用例--充值成功-1位小数--执行未通过
2021-03-27 12:44:14,159 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-27 12:44:14,159 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 503600.42, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:14,159 -- [test_recharge.py-->line:65] - ERROR: Decimal('600.10') != Decimal('600.1000000000000227373675443232059478759765625')
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 60, in test_recharge
    self.assertEqual(recharge_money, amount)
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('600.10') != Decimal('600.1000000000000227373675443232059478759765625')
2021-03-27 12:44:14,518 -- [test_recharge.py-->line:62] - ERROR: 用例--充值成功-2位小数--执行未通过
2021-03-27 12:44:14,518 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-27 12:44:14,518 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 504200.64, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:14,518 -- [test_recharge.py-->line:65] - ERROR: Decimal('600.22') != Decimal('600.220000000000027284841053187847137451171875')
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 60, in test_recharge
    self.assertEqual(recharge_money, amount)
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: Decimal('600.22') != Decimal('600.220000000000027284841053187847137451171875')
2021-03-27 12:44:14,939 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-50万--执行通过
2021-03-27 12:44:15,298 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:44:15,579 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:44:15,875 -- [test_recharge.py-->line:62] - ERROR: 用例--会员id为字符串--执行未通过
2021-03-27 12:44:15,875 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '数字格式化异常'}
2021-03-27 12:44:15,875 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 1004800.64, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:15,875 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:44:16,219 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为小数--执行通过
2021-03-27 12:44:16,593 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额为0--执行未通过
2021-03-27 12:44:16,593 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 12:44:16,593 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 1004800.64, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:16,593 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:44:16,921 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额为负数--执行通过
2021-03-27 12:44:17,248 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额为空--执行未通过
2021-03-27 12:44:17,248 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 1, 'msg': '充值金额为空'}
2021-03-27 12:44:17,248 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 2, 'msg': '余额必须为数值型', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:17,248 -- [test_recharge.py-->line:65] - ERROR: 2 != 1
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1
2021-03-27 12:44:17,545 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额-3位小数--执行未通过
2021-03-27 12:44:17,545 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额小数超过两位'}
2021-03-27 12:44:17,545 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 2, 'msg': '余额小数超过两位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:17,545 -- [test_recharge.py-->line:65] - ERROR: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 53, in test_recharge
    self.assertEqual(res["msg"], expected["msg"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 1202, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "E:\python\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '余额小数超过两位' != '金额小数超过两位'
- 余额小数超过两位
? ^
+ 金额小数超过两位
? ^

2021-03-27 12:44:17,872 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额-大于50万--执行未通过
2021-03-27 12:44:17,872 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 12:44:17,872 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 2, 'msg': '余额必须大于0并且小于或者等于500000', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:44:17,872 -- [test_recharge.py-->line:65] - ERROR: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 53, in test_recharge
    self.assertEqual(res["msg"], expected["msg"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 1202, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "E:\python\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '余额必须大于0并且小于或者等于500000' != '金额必须大于0并且小于或者等于500000'
- 余额必须大于0并且小于或者等于500000
? ^
+ 金额必须大于0并且小于或者等于500000
? ^

2021-03-27 12:44:18,153 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-非数字--执行通过
2021-03-27 12:44:18,387 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:57:52,065 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:57:58,352 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:57:58,679 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-整数--执行通过
2021-03-27 12:57:58,882 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-1位小数--执行通过
2021-03-27 12:57:59,163 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-2位小数--执行通过
2021-03-27 12:57:59,381 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-50万--执行通过
2021-03-27 12:57:59,490 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:57:59,615 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:57:59,740 -- [test_recharge.py-->line:62] - ERROR: 用例--会员id为字符串--执行未通过
2021-03-27 12:57:59,740 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '数字格式化异常'}
2021-03-27 12:57:59,740 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 1507200.96, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:57:59,740 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:57:59,865 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为小数--执行通过
2021-03-27 12:57:59,990 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额为0--执行未通过
2021-03-27 12:57:59,990 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 12:57:59,990 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 1507200.96, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:57:59,990 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:58:00,130 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额为负数--执行通过
2021-03-27 12:58:00,286 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额为空--执行通过
2021-03-27 12:58:00,395 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-3位小数--执行通过
2021-03-27 12:58:00,504 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-大于50万--执行通过
2021-03-27 12:58:00,614 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-非数字--执行通过
2021-03-27 12:58:00,754 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 12:58:10,838 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 12:58:15,705 -- [test_recharge.py-->line:69] - INFO: 用例--登录成功--执行通过
2021-03-27 12:58:16,080 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-整数--执行通过
2021-03-27 12:58:16,470 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-1位小数--执行通过
2021-03-27 12:58:16,813 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-2位小数--执行通过
2021-03-27 12:58:17,218 -- [test_recharge.py-->line:69] - INFO: 用例--充值成功-50万--执行通过
2021-03-27 12:58:17,484 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为空--执行通过
2021-03-27 12:58:17,733 -- [test_recharge.py-->line:69] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 12:58:18,014 -- [test_recharge.py-->line:62] - ERROR: 用例--会员id为字符串--执行未通过
2021-03-27 12:58:18,014 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '数字格式化异常'}
2021-03-27 12:58:18,014 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 2009601.28, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:58:18,014 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:58:18,310 -- [test_recharge.py-->line:69] - INFO: 用例--会员id为小数--执行通过
2021-03-27 12:58:18,544 -- [test_recharge.py-->line:62] - ERROR: 用例--充值金额为0--执行未通过
2021-03-27 12:58:18,544 -- [test_recharge.py-->line:63] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 12:58:18,544 -- [test_recharge.py-->line:64] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 2009601.28, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 12:58:18,544 -- [test_recharge.py-->line:65] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 52, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 12:58:18,841 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额为负数--执行通过
2021-03-27 12:58:19,122 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额为空--执行通过
2021-03-27 12:58:19,434 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-3位小数--执行通过
2021-03-27 12:58:19,699 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-大于50万--执行通过
2021-03-27 12:58:19,917 -- [test_recharge.py-->line:69] - INFO: 用例--充值金额-非数字--执行通过
2021-03-27 12:58:20,104 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------


2021-03-27 13:01:30,164 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 13:01:31,973 -- [test_recharge.py-->line:68] - INFO: 用例--登录成功--执行通过
2021-03-27 13:01:32,395 -- [test_recharge.py-->line:68] - INFO: 用例--充值成功-整数--执行通过
2021-03-27 13:01:32,753 -- [test_recharge.py-->line:68] - INFO: 用例--充值成功-1位小数--执行通过
2021-03-27 13:01:33,175 -- [test_recharge.py-->line:68] - INFO: 用例--充值成功-2位小数--执行通过
2021-03-27 13:01:33,565 -- [test_recharge.py-->line:68] - INFO: 用例--充值成功-50万--执行通过
2021-03-27 13:01:33,830 -- [test_recharge.py-->line:68] - INFO: 用例--会员id为空--执行通过
2021-03-27 13:01:34,064 -- [test_recharge.py-->line:68] - INFO: 用例--id不是当前登录的用户--执行通过
2021-03-27 13:01:34,313 -- [test_recharge.py-->line:61] - ERROR: 用例--会员id为字符串--执行未通过
2021-03-27 13:01:34,313 -- [test_recharge.py-->line:62] - DEBUG: 预期结果：{'code': 2, 'msg': '数字格式化异常'}
2021-03-27 13:01:34,313 -- [test_recharge.py-->line:63] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 2512001.6, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 13:01:34,329 -- [test_recharge.py-->line:64] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 51, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 13:01:34,532 -- [test_recharge.py-->line:68] - INFO: 用例--会员id为小数--执行通过
2021-03-27 13:01:34,766 -- [test_recharge.py-->line:61] - ERROR: 用例--充值金额为0--执行未通过
2021-03-27 13:01:34,766 -- [test_recharge.py-->line:62] - DEBUG: 预期结果：{'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
2021-03-27 13:01:34,766 -- [test_recharge.py-->line:63] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 2512001.6, 'mobile_phone': '13833336602', 'reg_name': '', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-27 13:01:34,766 -- [test_recharge.py-->line:64] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_recharge.py", line 51, in test_recharge
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-27 13:01:35,031 -- [test_recharge.py-->line:68] - INFO: 用例--充值金额为负数--执行通过
2021-03-27 13:01:35,312 -- [test_recharge.py-->line:68] - INFO: 用例--充值金额为空--执行通过
2021-03-27 13:01:35,546 -- [test_recharge.py-->line:68] - INFO: 用例--充值金额-3位小数--执行通过
2021-03-27 13:01:35,764 -- [test_recharge.py-->line:68] - INFO: 用例--充值金额-大于50万--执行通过
2021-03-27 13:01:35,983 -- [test_recharge.py-->line:68] - INFO: 用例--充值金额-非数字--执行通过
2021-03-27 13:01:36,373 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-27 21:05:55,334 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 21:06:20,076 -- [test_add.py-->line:63] - INFO: 用例--登录成功--执行通过
2021-03-27 21:06:20,372 -- [test_add.py-->line:63] - INFO: 用例--加标成功--执行通过
2021-03-27 21:06:20,435 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款人id为空--执行通过
2021-03-27 21:06:20,513 -- [test_add.py-->line:63] - INFO: 用例--加标失败—标题为空--执行通过
2021-03-27 21:06:20,560 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款金额为空--执行通过
2021-03-27 21:06:20,591 -- [test_add.py-->line:63] - INFO: 用例--加标失败—年利率为空--执行通过
2021-03-27 21:06:20,669 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款期限为空--执行通过
2021-03-27 21:06:20,716 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款期限类型为空--执行通过
2021-03-27 21:06:20,794 -- [test_add.py-->line:63] - INFO: 用例--加标失败—竞标天数为空--执行通过
2021-03-27 21:06:20,840 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款人id不是当前登录用户--执行通过
2021-03-27 21:06:20,887 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款金额为负数--执行通过
2021-03-27 21:06:20,965 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款金额为小数--执行通过
2021-03-27 21:06:21,106 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-27 21:07:10,667 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-27 21:07:12,352 -- [test_add.py-->line:63] - INFO: 用例--登录成功--执行通过
2021-03-27 21:07:12,991 -- [test_add.py-->line:63] - INFO: 用例--加标成功--执行通过
2021-03-27 21:07:13,303 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款人id为空--执行通过
2021-03-27 21:07:13,584 -- [test_add.py-->line:63] - INFO: 用例--加标失败—标题为空--执行通过
2021-03-27 21:07:13,880 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款金额为空--执行通过
2021-03-27 21:07:14,146 -- [test_add.py-->line:63] - INFO: 用例--加标失败—年利率为空--执行通过
2021-03-27 21:07:14,411 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款期限为空--执行通过
2021-03-27 21:07:14,676 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款期限类型为空--执行通过
2021-03-27 21:07:14,957 -- [test_add.py-->line:63] - INFO: 用例--加标失败—竞标天数为空--执行通过
2021-03-27 21:07:15,253 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款人id不是当前登录用户--执行通过
2021-03-27 21:07:15,518 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款金额为负数--执行通过
2021-03-27 21:07:15,955 -- [test_add.py-->line:63] - INFO: 用例--加标失败—借款金额为小数--执行通过
2021-03-27 21:07:16,189 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 12:01:38,454 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 12:01:52,932 -- [test_audit.py-->line:80] - INFO: 用例--审核通过--执行通过
2021-03-28 12:01:53,525 -- [test_audit.py-->line:80] - INFO: 用例--审核不通过--执行通过
2021-03-28 12:01:53,868 -- [test_audit.py-->line:80] - INFO: 用例--项目不在审核状态--执行通过
2021-03-28 12:01:54,164 -- [test_audit.py-->line:80] - INFO: 用例--审核状态为空--执行通过
2021-03-28 12:01:54,476 -- [test_audit.py-->line:80] - INFO: 用例--项目id为空--执行通过
2021-03-28 12:01:54,835 -- [test_audit.py-->line:80] - INFO: 用例--项目id不存在--执行通过
2021-03-28 12:01:55,147 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 12:13:16,493 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 12:13:19,379 -- [test_loans.py-->line:46] - INFO: 用例--获取成功:不填参数--执行通过
2021-03-28 12:13:19,676 -- [test_loans.py-->line:46] - INFO: 用例--获取成功:只填页面参数--执行通过
2021-03-28 12:13:20,003 -- [test_loans.py-->line:46] - INFO: 用例--获取成功:只填页面内容数--执行通过
2021-03-28 12:13:20,331 -- [test_loans.py-->line:46] - INFO: 用例--获取成功:都填参数--执行通过
2021-03-28 12:13:20,581 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 12:29:15,753 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 12:29:18,746 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-03-28 12:29:19,086 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-03-28 12:29:19,392 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 12:36:29,692 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 12:36:31,688 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-03-28 12:36:31,954 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-03-28 12:36:32,203 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 12:46:21,021 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 12:46:23,518 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-03-28 12:46:23,783 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-03-28 12:46:24,017 -- [test_update.py-->line:55] - INFO: 用例--登录成功--执行通过
2021-03-28 12:46:24,251 -- [test_update.py-->line:48] - ERROR: 用例--正常修改昵称—用户名长度10位--执行未通过
2021-03-28 12:46:24,251 -- [test_update.py-->line:49] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 12:46:24,251 -- [test_update.py-->line:50] - DEBUG: 实际结果：{'code': 2, 'msg': '用户昵称长度超过10位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 12:46:24,251 -- [test_update.py-->line:51] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_update.py", line 45, in test_update
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 12:46:24,548 -- [test_update.py-->line:55] - INFO: 用例--用户id为空--执行通过
2021-03-28 12:46:24,797 -- [test_update.py-->line:55] - INFO: 用例--修改的用户名为空--执行通过
2021-03-28 12:46:25,063 -- [test_update.py-->line:55] - INFO: 用例--用户名长度11位--执行通过
2021-03-28 12:46:25,312 -- [test_update.py-->line:48] - ERROR: 用例--用户id非数字类型--执行未通过
2021-03-28 12:46:25,312 -- [test_update.py-->line:49] - DEBUG: 预期结果：{'code': 2, 'msg': '参数类型错误'}
2021-03-28 12:46:25,312 -- [test_update.py-->line:50] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 2512001.6, 'mobile_phone': '13833336602', 'reg_name': '木森667@%', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 12:46:25,312 -- [test_update.py-->line:51] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_update.py", line 45, in test_update
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-28 12:46:25,546 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 12:50:07,982 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 12:50:09,808 -- [test_update.py-->line:55] - INFO: 用例--登录成功--执行通过
2021-03-28 12:50:10,057 -- [test_update.py-->line:55] - INFO: 用例--正常修改昵称—用户名长度10位--执行通过
2021-03-28 12:50:10,525 -- [test_update.py-->line:55] - INFO: 用例--用户id为空--执行通过
2021-03-28 12:50:10,759 -- [test_update.py-->line:55] - INFO: 用例--修改的用户名为空--执行通过
2021-03-28 12:50:11,024 -- [test_update.py-->line:55] - INFO: 用例--用户名长度11位--执行通过
2021-03-28 12:50:11,274 -- [test_update.py-->line:48] - ERROR: 用例--用户id非数字类型--执行未通过
2021-03-28 12:50:11,274 -- [test_update.py-->line:49] - DEBUG: 预期结果：{'code': 2, 'msg': '参数类型错误'}
2021-03-28 12:50:11,274 -- [test_update.py-->line:50] - DEBUG: 实际结果：{'code': 0, 'msg': 'OK', 'data': {'id': 1000294859, 'leave_amount': 2512001.6, 'mobile_phone': '13833336602', 'reg_name': '木森667@%', 'reg_time': '2021-03-27 11:53:23.0', 'type': 1}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 12:50:11,274 -- [test_update.py-->line:51] - ERROR: 0 != 2
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_update.py", line 45, in test_update
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2021-03-28 12:50:11,461 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 17:10:11,932 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 17:10:27,283 -- [test_invest.py-->line:119] - ERROR: 用例--投资人正常投资--执行未通过
2021-03-28 17:10:27,283 -- [test_invest.py-->line:120] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 17:10:27,283 -- [test_invest.py-->line:121] - DEBUG: 实际结果：{'code': 2, 'msg': '该项目不在竞标中状态', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 17:10:27,283 -- [test_invest.py-->line:122] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_invest.py", line 90, in test_invest
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 17:10:28,000 -- [test_invest.py-->line:126] - INFO: 用例--投资人id为空--执行通过
2021-03-28 17:10:28,390 -- [test_invest.py-->line:126] - INFO: 用例--标id为空--执行通过
2021-03-28 17:10:28,733 -- [test_invest.py-->line:126] - INFO: 用例--投资金额为空--执行通过
2021-03-28 17:10:29,077 -- [test_invest.py-->line:119] - ERROR: 用例--满标--执行未通过
2021-03-28 17:10:29,077 -- [test_invest.py-->line:120] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 17:10:29,077 -- [test_invest.py-->line:121] - DEBUG: 实际结果：{'code': 2, 'msg': '该项目不在竞标中状态', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 17:10:29,077 -- [test_invest.py-->line:122] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_invest.py", line 90, in test_invest
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 17:10:29,545 -- [test_invest.py-->line:119] - ERROR: 用例--投资金额大于可投金额--执行未通过
2021-03-28 17:10:29,545 -- [test_invest.py-->line:120] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 17:10:29,545 -- [test_invest.py-->line:121] - DEBUG: 实际结果：{'code': 2, 'msg': '该项目不在竞标中状态', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 17:10:29,545 -- [test_invest.py-->line:122] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_invest.py", line 90, in test_invest
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 17:10:30,091 -- [test_invest.py-->line:119] - ERROR: 用例--投资金额不能被100整除--执行未通过
2021-03-28 17:10:30,091 -- [test_invest.py-->line:120] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 17:10:30,091 -- [test_invest.py-->line:121] - DEBUG: 实际结果：{'code': 2, 'msg': '充值金额必须大于100，并且可以被100整除', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 17:10:30,091 -- [test_invest.py-->line:122] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_invest.py", line 90, in test_invest
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 17:10:30,356 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 17:27:35,028 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 17:27:37,259 -- [test_invest.py-->line:128] - INFO: 用例--投资人id为空--执行通过
2021-03-28 17:27:37,602 -- [test_invest.py-->line:128] - INFO: 用例--标id为空--执行通过
2021-03-28 17:27:37,992 -- [test_invest.py-->line:128] - INFO: 用例--投资金额为空--执行通过
2021-03-28 17:27:38,491 -- [test_invest.py-->line:120] - ERROR: 用例--投资金额大于可投金额--执行未通过
2021-03-28 17:27:38,491 -- [test_invest.py-->line:121] - DEBUG: 请求数据：{'member_id': 1000296302, 'loan_id': 2030637, 'amount': 30000}
2021-03-28 17:27:38,491 -- [test_invest.py-->line:122] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 17:27:38,491 -- [test_invest.py-->line:123] - DEBUG: 实际结果：{'code': 2, 'msg': '该项目不在竞标中状态', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 17:27:38,491 -- [test_invest.py-->line:124] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_invest.py", line 91, in test_invest
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 17:27:38,819 -- [test_invest.py-->line:128] - INFO: 用例--投资金额不能被100整除--执行通过
2021-03-28 17:27:39,037 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 17:29:17,622 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 17:35:21,076 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 17:35:23,681 -- [test_invest.py-->line:128] - INFO: 用例--投资人id为空--执行通过
2021-03-28 17:35:24,009 -- [test_invest.py-->line:128] - INFO: 用例--标id为空--执行通过
2021-03-28 17:35:24,430 -- [test_invest.py-->line:128] - INFO: 用例--投资金额为空--执行通过
2021-03-28 17:35:24,914 -- [test_invest.py-->line:120] - ERROR: 用例--投资金额大于可投金额--执行未通过
2021-03-28 17:35:24,914 -- [test_invest.py-->line:121] - DEBUG: 请求数据：{'member_id': 1000296302, 'loan_id': 2030647, 'amount': 30000}
2021-03-28 17:35:24,914 -- [test_invest.py-->line:122] - DEBUG: 预期结果：{'code': 0, 'msg': 'OK'}
2021-03-28 17:35:24,914 -- [test_invest.py-->line:123] - DEBUG: 实际结果：{'code': 2, 'msg': '该标可投金额不足,可投金额：2000.0', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
2021-03-28 17:35:24,914 -- [test_invest.py-->line:124] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\ningmengban\interface_test\testcase\test_invest.py", line 91, in test_invest
    self.assertEqual(res["code"], expected["code"])
  File "E:\python\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "E:\python\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
2021-03-28 17:35:25,273 -- [test_invest.py-->line:128] - INFO: 用例--投资金额不能被100整除--执行通过
2021-03-28 17:35:25,491 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 17:44:31,045 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 17:44:36,272 -- [test_invest.py-->line:128] - INFO: 用例--投资人正常投资--执行通过
2021-03-28 17:44:36,646 -- [test_invest.py-->line:128] - INFO: 用例--投资人id为空--执行通过
2021-03-28 17:44:37,052 -- [test_invest.py-->line:128] - INFO: 用例--标id为空--执行通过
2021-03-28 17:44:37,379 -- [test_invest.py-->line:128] - INFO: 用例--投资金额为空--执行通过
2021-03-28 17:44:38,269 -- [test_invest.py-->line:128] - INFO: 用例--满标--执行通过
2021-03-28 17:44:38,581 -- [test_invest.py-->line:128] - INFO: 用例--投资金额大于可投金额--执行通过
2021-03-28 17:44:38,971 -- [test_invest.py-->line:128] - INFO: 用例--投资金额不能被100整除--执行通过
2021-03-28 17:44:39,189 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 18:22:40,517 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 18:22:42,311 -- [test_main_stream.py-->line:60] - INFO: 用例--登录成功--执行通过
2021-03-28 18:22:42,576 -- [test_main_stream.py-->line:60] - INFO: 用例--加标成功--执行通过
2021-03-28 18:22:43,371 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-03-28 18:26:44,364 -- [run.py-->line:6] - INFO: ---------------开始执行测试用例-----------------------
2021-03-28 18:26:47,640 -- [test_main_stream.py-->line:60] - INFO: 用例--管理员注册--执行通过
2021-03-28 18:26:47,983 -- [test_main_stream.py-->line:60] - INFO: 用例--管理员正常登录--执行通过
2021-03-28 18:26:48,249 -- [test_main_stream.py-->line:60] - INFO: 用例--管理员加标--执行通过
2021-03-28 18:26:48,498 -- [test_main_stream.py-->line:60] - INFO: 用例--管理员审核--执行通过
2021-03-28 18:26:49,075 -- [test_main_stream.py-->line:60] - INFO: 用例--投资人注册--执行通过
2021-03-28 18:26:49,465 -- [test_main_stream.py-->line:60] - INFO: 用例--投资人正常登录--执行通过
2021-03-28 18:26:49,746 -- [test_main_stream.py-->line:60] - INFO: 用例--获取用户信息--执行通过
2021-03-28 18:26:50,043 -- [test_main_stream.py-->line:60] - INFO: 用例--更改昵称--执行通过
2021-03-28 18:26:50,323 -- [test_main_stream.py-->line:60] - INFO: 用例--充值--执行通过
2021-03-28 18:26:50,589 -- [test_main_stream.py-->line:60] - INFO: 用例--投资人正常投资--执行通过
2021-03-28 18:26:50,807 -- [test_main_stream.py-->line:60] - INFO: 用例--取现--执行通过
2021-03-28 18:26:51,041 -- [test_main_stream.py-->line:60] - INFO: 用例--获取项目列表--执行通过
2021-03-28 18:26:51,244 -- [run.py-->line:14] - INFO: ---------------测试用例执行完毕-----------------------





2021-05-08 17:00:00,793 -- [run.py-->line:7] - INFO: ---------------开始执行测试用例-----------------------
2021-05-08 17:00:21,713 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-05-08 17:00:22,347 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-05-08 17:00:22,689 -- [run.py-->line:19] - INFO: ---------------测试用例执行完毕-----------------------





2021-05-08 17:06:54,079 -- [run.py-->line:8] - INFO: ---------------开始执行测试用例-----------------------
2021-05-08 17:06:56,798 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-05-08 17:06:57,173 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-05-08 17:06:57,451 -- [run.py-->line:20] - INFO: ---------------测试用例执行完毕-----------------------





2021-05-16 10:07:14,182 -- [run.py-->line:8] - INFO: ---------------开始执行测试用例-----------------------
2021-05-16 10:07:34,491 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-05-16 10:07:34,895 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-05-16 10:07:35,165 -- [run.py-->line:20] - INFO: ---------------测试用例执行完毕-----------------------





2021-05-16 10:07:43,874 -- [run.py-->line:8] - INFO: ---------------开始执行测试用例-----------------------
2021-05-16 10:07:45,747 -- [test_info.py-->line:56] - INFO: 用例--正常获取用户信息--执行通过
2021-05-16 10:07:46,039 -- [test_info.py-->line:56] - INFO: 用例--不存在的用户id--执行通过
2021-05-16 10:07:46,301 -- [run.py-->line:20] - INFO: ---------------测试用例执行完毕-----------------------





